[package]
name = "ssr-one-of"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"

s_text_input_f.workspace = true
s_text_input_f-parser.workspace = true

ssr-algorithms.workspace = true
ssr-facade.workspace = true
ssr-core.workspace = true
