[package]
name = "ssr-facade"
description = "implementation of ssr-core TasksFacade trait"
version = "0.10.2"
license = "MIT"
edition = "2024"

[dependencies]
itertools = "0.14"
rand = "0.9"
s_text_input_f.workspace = true
serde.workspace = true
ssr-core.workspace = true
