[package]
name = "s_text_input_f-parser"
description = "parser for sineptic text input format"
license = "MIT"
version = "0.2.0"
edition = "2024"

[dependencies]
chumsky = "0.9"
s_text_input_f.workspace = true
