[package]
name = "ssr-core"
description = "traits for spaced repetition libs"
repository = "https://github.com/sineptic/ssr-core"
license = "MIT"
version = "0.38.0"
edition = "2024"

[dependencies]
s_text_input_f.workspace = true
serde.workspace = true
thiserror = "2.0"
