name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nightly version
        run: rustup override set nightly
          && rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --check
      - name: Linter
        run: cargo clippy -- -Dwarnings

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows]
    needs: check

    steps:
      - uses: actions/checkout@v4
      - name: Use nightly version
        run: rustup override set nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ssr-${{ matrix.os }}-x86_64
          path: |
            target/release/ssr
            target/release/ssr.exe
          if-no-files-found: error
